services:
  frontend:
    build:
      context: .
      dockerfile: DockerfileFront
    container_name: frontend
    ports:
      - 8080:8080

  backend:
    build:
      context: .
      dockerfile: DockerfileBack
    container_name: backend
    links:
      - blender
    ports:
      - 3030:3030

  blender:
    image: nytimes/blender:2.92-gpu-ubuntu18.04
    container_name: blender
