version: "3.8"
services:
  frontend:
    build:
      context: ./backend
      dockerfile: ./backend/DockerfileFront
    container_name: frontend
    ports:
      - 8080:8080

  backend:
    build:
      context: ./frontend
      dockerfile: ./frontend/DockerfileBack
    container_name: backend
    ports:
      - 3030:3030
